version: "3.9"

services:
  peer1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peer1
    environment:
      BOOTSTRAP_HOST: host.docker.internal
      BOOTSTRAP_PORT: 8080
      PEER_PORT: 9001
    ports:
      - "9001:9001"
    networks:
      - p2pnet

  peer2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peer2
    environment:
      BOOTSTRAP_HOST: host.docker.internal
      BOOTSTRAP_PORT: 8080
      PEER_PORT: 9002
    ports:
      - "9002:9002"
    networks:
      - p2pnet

networks:
  p2pnet:
    driver: bridge
