version: "3.9"

services:
  peer1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peer1
    stdin_open: true
    tty: true
    environment:
      BOOTSTRAP_HOST: host.docker.internal
      BOOTSTRAP_PORT: 9001
      PEER_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - p2pnet

  peer2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peer2
    stdin_open: true
    tty: true
    environment:
      BOOTSTRAP_HOST: host.docker.internal
      BOOTSTRAP_PORT: 9001
      PEER_PORT: 8082
    ports:
      - "8082:8082"
    networks:
      - p2pnet

networks:
  p2pnet:
    driver: bridge
